Enhance ClamAV refresh workflow to include validation of version format

diff --git a/.github/workflows/scheduled-clamav-refresh.yml b/.github/workflows/scheduled-clamav-refresh.yml
--- a/.github/workflows/scheduled-clamav-refresh.yml
+++ b/.github/workflows/scheduled-clamav-refresh.yml
@@ -17,9 +17,11 @@ jobs:
       - name: Refresh ClamAV version
         run: echo $(dig +short current.cvd.clamav.net txt | tr -d '"') > current.cvd.clamav.net.txt
 
-      - name: Print diff
+      - name: Print diff & validate
         run: |
           git diff current.cvd.clamav.net.txt
+          grep -Eqx '^\d+\.\d+\.\d+:\d+:\d+:\d+:\d+:\d+:\d+:\d+$' current.cvd.clamav.net.txt || echo 'REGEX PATTERN FAILED TO MATCH'
+
 
       - name: Add, Commit & Push changes
         uses: EndBug/add-and-commit@v9.1.4
